# == Variables ==
# 
# You can define here your project Variables.
#
Variables:
<!--
  Dear Bug Hunter,
  This credential is intentionally included for educational purposes only and does not provide access to any production systems.
  Please do not submit it as part of our bug bounty program.
-->
  CLIENT_ID: ''
  
  CLIENT_SECRET: ''
  
  TENANT_ID: ''
  
  END_POINT: ''
  
  TEST_CONTAINTER: ''